export enum AppPage {
  Home = 'Home',
  ProblemList = 'ProblemList',
  ProblemDetail = 'ProblemDetail',
  ContestList = 'ContestList',
  ContestDetail = 'ContestDetail',
  Ranking = 'Ranking',
  Blog = 'Blog',
  UserProfile = 'UserProfile',
  Search = 'Search',
  Training = 'Training',
  Team = 'Team',
  Record = 'Record',
  Login = 'Login',
  Messages = 'Messages',
  Solution = 'Solution',
  Article = 'Article',
  UserSetting = 'UserSetting',
  MyProblems = 'MyProblems',
  MyContests = 'MyContests',
  TrainingFav = 'TrainingFav',
  Notification = 'Notification',
  Practice = 'Practice',
  CreatedContests = 'CreatedContests',
  CreatedTrainings = 'CreatedTrainings',
}

export enum HomeSubPage {
  Trending = 'Trending',
  RecentContests = 'RecentContests',
  HotProblems = 'HotProblems',
  RecentDiscussions = 'RecentDiscussions',
}
