// Triggers UnoCSS to generate icon CSS classes (scanned from string literals)
export const iconSafelist = [
  'i-mingcute:home-4-line',
  'i-mingcute:home-4-fill',
  'i-mingcute:code-line',
  'i-mingcute:code-fill',
  'i-mingcute:trophy-line',
  'i-mingcute:trophy-fill',
  'i-mingcute:chart-bar-line',
  'i-mingcute:chart-bar-fill',
  'i-mingcute:comment-line',
  'i-mingcute:comment-fill',
  'i-mingcute:book-4-line',
  'i-mingcute:book-4-fill',
  'i-mingcute:time-line',
  'i-mingcute:time-fill',
  'i-mingcute:settings-3-line',
  'i-line-md:sunny-outline-to-moon-loop-transition',
  'i-line-md:moon-alt-to-sunny-outline-loop-transition',
  'i-line-md:sunny-outline-to-moon-transition',
  'i-line-md:moon-to-sunny-outline-transition',
  'i-line-md:rotate-270',
  'i-line-md:arrow-small-up',
  'i-svg-spinners:ring-resize',
]
