// Extract only the icons actually referenced in src/ from the full
// @iconify/json collections (line-md, mingcute), writing a slim
// src/utils/icon-data.ts. Re-run after adding/removing icon references.
//
// Strategy (favor inclusion — false positives are harmless, false negatives
// break the UI): load each collection's full name set, then scan every quoted
// string in src/. Any token equal to a real icon name, or appearing as
// `(i-)?<prefix>:<name>`, pulls that icon in.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, extname } from 'node:path'

const ROOT = process.cwd()
const SRC = join(ROOT, 'src')
const COLLECTIONS = ['mingcute', 'line-md']

// 1. Load full collections -> { name -> iconData } + width/height
const full = {}
for (const c of COLLECTIONS) {
  const j = JSON.parse(readFileSync(join(ROOT, 'node_modules/@iconify/json/json', `${c}.json`), 'utf8'))
  full[c] = { icons: j.icons, width: j.width || 24, height: j.height || 24, names: new Set(Object.keys(j.icons)) }
}

// 2. Collect every source file
const files = []
function walk(dir) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    const s = statSync(p)
    if (s.isDirectory()) walk(p)
    else if (/\.(vue|ts|tsx|js|mjs)$/.test(extname(p))) files.push(p)
  }
}
walk(SRC)

// 3. Scan for icon references
const needed = Object.fromEntries(COLLECTIONS.map(c => [c, new Set()]))
const prefixed = /(?:i-)?(mingcute|line-md):([a-z0-9-]+)/g
const quoted = /['"`]([a-z][a-z0-9-]{2,})['"`]/g

for (const f of files) {
  const txt = readFileSync(f, 'utf8')
  let m
  while ((m = prefixed.exec(txt))) {
    const [, col, name] = m
    if (full[col]?.names.has(name)) needed[col].add(name)
  }
  while ((m = quoted.exec(txt))) {
    const tok = m[1]
    for (const col of COLLECTIONS) {
      if (full[col].names.has(tok)) needed[col].add(tok)
    }
  }
}

// 4. Build slim collections in the shape icons.ts expects
function slim(col) {
  const f = full[col]
  const icons = {}
  for (const name of [...needed[col]].sort()) {
    if (f.icons[name]) icons[name] = f.icons[name]
  }
  return { icons, width: f.width, height: f.height }
}

const mingcute = slim('mingcute')
const lineMd = slim('line-md')

// 5. Emit src/utils/icon-data.ts
const out = `// AUTO-GENERATED by scripts/extract-icons.mjs — do not edit by hand.
// Slim subset of @iconify/json (mingcute + line-md) containing only the icons
// referenced in src/. Re-run the script after changing icon usage.

export interface SlimIcon { body: string; width?: number; height?: number }
export interface SlimCollection { icons: Record<string, SlimIcon>; width: number; height: number }

export const mingcuteIcons: SlimCollection = ${JSON.stringify(mingcute)}
export const lineMdIcons: SlimCollection = ${JSON.stringify(lineMd)}
`
writeFileSync(join(ROOT, 'src/utils/icon-data.ts'), out)

console.log(`extracted: mingcute ${needed.mingcute.size} icons, line-md ${needed['line-md'].size} icons`)
console.log(`written: src/utils/icon-data.ts (${(out.length / 1024).toFixed(1)} KB)`)
